### ISSUE TITLE
TreeViewProtocol support

### ISSUE THREAD

**Issue by danilbykov** [ckipp01/coc-metals#7]
I have implemented basic support for TreeViewProtocol. It is far from completion for now but at least trees are loaded and rendered in vim. I'm going to implement more hotkeys, configuration settings, better buffer management and so on.

If you want, I can port my changes into your repository.

**Comment by ckipp01** [comment]
Hey! I'd love to see how it's implemented. Do you have it in a repo yet?

I'm totally open to having you try and port it over, however, depending on how it's implemented may determine how difficult that is. `coc-metals` is tied in pretty tightly to `coc.nvim`, and I'm not 100% sure on the best way to implement the treeViews yet it since it'd probably be best to implement it utilizing just pure vimscript, but done in a way that it can still play nicely with `coc.nvim`.

I'd say if it's not pushed up yet into a repo, do that, and then we can take a look at it and brainstorm how you might be able to port it in.

**Comment by danilbykov** [comment]
Sorry, I had to review code in your repository better. I thought you forked coc.nvim. But you didn't. This is what I did for my experiments.

So I will continue to implement TreeViewProtocol inside my repository.

**Comment by ckipp01** [comment]
Sounds good, and good luck! If you get to a point where you do want to try and implement one via an extension rather than forking coc.nvim, feel free to shoot me a message!
